// Generated by gencpp from file bliss/GlobalDescriptor.msg
// DO NOT EDIT!


#ifndef BLISS_MESSAGE_GLOBALDESCRIPTOR_H
#define BLISS_MESSAGE_GLOBALDESCRIPTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bliss
{
template <class ContainerAllocator>
struct GlobalDescriptor_
{
  typedef GlobalDescriptor_<ContainerAllocator> Type;

  GlobalDescriptor_()
    : header()
    , type(0)
    , info()
    , data()  {
    }
  GlobalDescriptor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , info(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _type_type;
  _type_type type;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _info_type;
  _info_type info;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::bliss::GlobalDescriptor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bliss::GlobalDescriptor_<ContainerAllocator> const> ConstPtr;

}; // struct GlobalDescriptor_

typedef ::bliss::GlobalDescriptor_<std::allocator<void> > GlobalDescriptor;

typedef boost::shared_ptr< ::bliss::GlobalDescriptor > GlobalDescriptorPtr;
typedef boost::shared_ptr< ::bliss::GlobalDescriptor const> GlobalDescriptorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bliss::GlobalDescriptor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bliss::GlobalDescriptor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bliss::GlobalDescriptor_<ContainerAllocator1> & lhs, const ::bliss::GlobalDescriptor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.info == rhs.info &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bliss::GlobalDescriptor_<ContainerAllocator1> & lhs, const ::bliss::GlobalDescriptor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bliss

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bliss::GlobalDescriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bliss::GlobalDescriptor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bliss::GlobalDescriptor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bliss::GlobalDescriptor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bliss::GlobalDescriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bliss::GlobalDescriptor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bliss::GlobalDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cea16e5cbeb4de779e68853766f4772e";
  }

  static const char* value(const ::bliss::GlobalDescriptor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcea16e5cbeb4de77ULL;
  static const uint64_t static_value2 = 0x9e68853766f4772eULL;
};

template<class ContainerAllocator>
struct DataType< ::bliss::GlobalDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bliss/GlobalDescriptor";
  }

  static const char* value(const ::bliss::GlobalDescriptor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bliss::GlobalDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"\n"
"# compressed global descriptor\n"
"# use rtabmap::util3d::uncompressData() from \"rtabmap/core/util3d.h\"\n"
"int32 type\n"
"uint8[] info\n"
"uint8[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bliss::GlobalDescriptor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bliss::GlobalDescriptor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.info);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlobalDescriptor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bliss::GlobalDescriptor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bliss::GlobalDescriptor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "info[]" << std::endl;
    for (size_t i = 0; i < v.info.size(); ++i)
    {
      s << indent << "  info[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.info[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLISS_MESSAGE_GLOBALDESCRIPTOR_H
